In [ ]:
## Python DAY:7

In [82]:
#1.Write a Python program to generate a random alphabetical string, random value between two integers (inclusive) and a random multiple of 7 between 0 and 70. 

import random
import string

str1 = random.choice(string.ascii_letters)
print("Random alphabatical string",str1)

num = random.randint(1,4)
print("Random number between two int:",num)

mlti_7 = random.randrange(0,70, 7)
print("random Multiple of 7 :",mlti_7)

Random alphabatical string T
Random number between two int: 3
random Multiple of 7 : 35


In [102]:
#2.Write a python program to create a package (Atgeir),subpackage(Data),modules(Learner) and create read and write function to module

from Atgeir.Data.learner import *

print(read('sayanik'))
print(write('Mukherjee'))

sayanik
Mukherjee


In [93]:
#3.write a python program to print the no. of days to reach your birthday from today

import datetime

birth = datetime.date(1959,1,22)
print("birth day:",birth)

today = datetime.date.today()
print("Today:",today)

if (today.month==birth.month and today.day>=birth.day or today.month > birth.month):
    nextbirthyear=today.year +1
else:
    nextbirthyear=today.year
    
nextbirthday = datetime.date(nextbirthyear,birth.month,birth.day)
print("Nextbirthday :",nextbirthday)

differnece = nextbirthday-today
print("days left for next birthday:",differnece.days)

birth day: 1959-01-22
Today: 2022-07-08
Nextbirthday : 2023-01-22
days left for next birthday: 198


In [97]:
#4.Write a Python program to get a list of locally installed Python modules

help('modules')


Please wait a moment while I gather a list of all available modules...



C:\Users\SAYANIK\anaconda3\lib\pkgutil.py:93: MatplotlibDeprecationWarning: 
The matplotlib.compat module was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  __import__(info.name)
C:\Users\SAYANIK\anaconda3\lib\site-packages\nltk\twitter\__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn(


Update LANGUAGE_CODES (inside config/base.py) if a new translation has been added to Spyder


QSS file sucessfuly loaded.
Found application patches to be applied.
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
C:\Users\SAYANIK\anaconda3\lib\pkgutil.py:108: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  yield from walk_packages(path, info.name+'.', onerror)


Cython              codecs              modulefinder        sortedcontainers
IPython             codeop              more_itertools      soupsieve
OpenSSL             collections         mpmath              sphinx
PIL                 colorama            msgpack             sphinxcontrib
PyQt5               colorsys            msilib              spyder
TBB                 commctrl            msvcrt              spyder_kernels
__future__          compileall          multipledispatch    sqlalchemy
_abc                comtypes            multiprocessing     sqlite3
_aix_support        concurrent          munkres             sre_compile
_ast                conda               mypy_extensions     sre_constants
_asyncio            conda_build         nacl                sre_parse
_bisect             conda_content_trust navigator_updater   ssl
_black_version      conda_env           nbclassic           sspi
_blake2             conda_pack          nbclient            sspicon
_bootlocale       

In [9]:
import numpy as np
!pip install numpy

In [28]:
#5.a) A 1-D array called ‘zeros’ having 10 elements and all the elements are set to zero.
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
#5.b) 1-D array called ‘vowels’ having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.

vowels = np.array(['a','e','i','o','u'])
vowels

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

In [29]:
#5.c) A 2-D array called ‘ones’ having 2 rows and 5 columns and all the elements are set to 1 and dtype as int

ones = np.ones((2,5),dtype=int)
ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
#5.d) Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7, -2, -19, 0, 3.4, 99.9, 10.6, 0, 13

lst1 = [[2.7, -2, -19], [0, 3.4, 99.9], [10.6, 0, 1]]
myarray1 = np.array(lst1)
myarray1
#print(myarray1.shape)

array([[  2.7,  -2. , -19. ],
       [  0. ,   3.4,  99.9],
       [ 10.6,   0. ,   1. ]])

In [49]:
#5.e) A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float

myarray2 = np.arange(4,64,4,dtype=float).reshape(3,5)
myarray2

array([[ 4.,  8., 12., 16., 20.],
       [24., 28., 32., 36., 40.],
       [44., 48., 52., 56., 60.]])

In [35]:
#6.a) Find the dimensions, shape, size, data type of the items and itemsize of arrays ‘zeros’, ‘vowels’, ‘ones’, myarray1 and myarray2

print(zeros.shape)
print(zeros.size)
print(zeros.ndim)
print(zeros.dtype)
print(zeros.itemsize)   # returns the size (in bytes) of each element of a NumPy array

(10,)
10
1
float64
8


In [36]:
# array vowels
print(vowels.shape)
print(vowels.size)
print(vowels.ndim)
print(vowels.dtype)
print(vowels.itemsize)

(5,)
5
1
<U1
4


In [37]:
# array ones
print(ones.shape)
print(ones.size)
print(ones.ndim)
print(ones.dtype)
print(ones.itemsize)

(2, 5)
10
2
int32
4


In [38]:
#array myarray1 
print(myarray1.shape)
print(myarray1.size)
print(myarray1.ndim)
print(myarray1.dtype)
print(myarray1.itemsize)

(3, 3)
9
2
float64
8


In [39]:
#array myarray2
print(myarray2.shape)
print(myarray2.size)
print(myarray2.ndim)
print(myarray2.dtype)
print(myarray2.itemsize)

(3, 5)
15
2
float64
8


In [42]:
#6.b) Reshape the array ‘ones’ to have all the 10 elements in a single row.

ones_1 = ones.reshape(1,10)
ones_1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [46]:
#6.c) Display the 2nd and 3rd element of the array ‘vowels’

vowels[1:3]

array(['e', 'i'], dtype='<U1')

In [50]:
#6.d) Display all elements in the 2nd and 3rd row of the array ‘myarray1’.

myarray1[1:3,:]

array([[ 0. ,  3.4, 99.9],
       [10.6,  0. ,  1. ]])

In [52]:
#6.e) Display the elements in the 1st and 2nd column of the array ‘myarray1’.

myarray1[:,:2]

array([[ 2.7, -2. ],
       [ 0. ,  3.4],
       [10.6,  0. ]])

In [56]:
#6.f) Display the elements in the 1st column of the 2nd and 3rd row of the array ‘myarray1’

myarray1[1:,0]

array([ 0. , 10.6])

In [58]:
#6.g) Reverse the array of ‘vowels’.

vowels[::-1]

array(['u', 'o', 'i', 'e', 'a'], dtype='<U1')